const CVS_VERSION='V240_CVS_VENDOR_DB_SEPARATE_PAGE_20260706';
let cvsData=null;
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[s]));
const norm=v=>String(v??'').toLowerCase();
function safeUrl(url){try{const u=new URL(url, location.href);return ['http:','https:'].includes(u.protocol)?u.href:''}catch{return ''}}
async function refreshMarketBaseCache(){try{const keys=await caches.keys();await Promise.all(keys.filter(k=>k.includes('market_base')||k.includes('MARKET_BASE')).map(k=>caches.delete(k)));if('serviceWorker'in navigator){const regs=await navigator.serviceWorker.getRegistrations();await Promise.all(regs.filter(r=>String(r.scope||'').includes('/market_base/')).map(r=>r.unregister()));}location.href=location.pathname+'?v=240&refresh='+Date.now();}catch(e){location.reload();}}
function fillStats(){const m=cvsData.metadata;const rows=[['会社',m.public_display_company_count],['工場・拠点',m.facility_count],['商品ラベル参考',m.label_reference_count],['国・地域',m.country_count]];$('#cvsStats').innerHTML=rows.map(([k,v])=>`<div class="cvs-stat"><strong>${esc(v)}</strong><span>${esc(k)}</span></div>`).join('')}
function setupFilters(){const countries=[...new Set(cvsData.companies.map(x=>x.country_region).filter(Boolean))].sort();$('#cvsCountry').innerHTML='<option value="all">すべての国・地域</option>'+countries.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('');const statuses=[...new Set(cvsData.companies.map(x=>x.display_status).filter(Boolean))].sort();$('#cvsStatus').innerHTML='<option value="all">表示状態すべて</option>'+statuses.map(s=>`<option value="${esc(s)}">${esc(s)}</option>`).join('')}
function renderCountries(){const rows=cvsData.countries.slice(0,12);$('#cvsCountryGrid').innerHTML=rows.map(c=>`<article class="cvs-country-card"><h4>${esc(c.country_region)}</h4><div class="cvs-mini"><span>会社 ${esc(c.company_count)}</span><span>工場 ${esc(c.facility_count)}</span><span>ラベル ${esc(c.label_reference_count)}</span><span>出典 ${esc(c.source_count)}</span></div><button data-country="${esc(c.country_region)}">この国を見る</button></article>`).join('')}
function searchBlob(c){return norm([c.company_name,c.country_region,c.related_cvs_chains,c.business_product_category,c.main_locations,c.rice_related,...(c.facilities||[]).map(f=>[f.factory_name,f.city_area,f.main_products].join(' ')),...(c.product_label_references||[]).map(l=>[l.product_name,l.manufacturer,l.product_category].join(' '))].join(' '))}
function renderCards(){const q=norm($('#cvsSearch').value);const country=$('#cvsCountry').value;const status=$('#cvsStatus').value;const flag=$('#cvsFlag').value;let rows=cvsData.companies.filter(c=>!q||searchBlob(c).includes(q));if(country!=='all')rows=rows.filter(c=>c.country_region===country);if(status!=='all')rows=rows.filter(c=>c.display_status===status);if(flag==='facility')rows=rows.filter(c=>Number(c.facility_count)>0);if(flag==='label')rows=rows.filter(c=>Number(c.label_reference_count)>0);if(flag==='rice')rows=rows.filter(c=>norm(c.rice_related).includes('米')||norm(c.business_product_category).includes('米飯')||norm(c.business_product_category).includes('おにぎり'));
 $('#cvsCount').textContent=`表示 ${rows.length}件`;$('#cvsCards').innerHTML=rows.map(card).join('')||'<p class="empty-cvs">該当する会社がありません。</p>'}
function card(c){const tags=[c.country_region,c.display_status,Number(c.facility_count)>0?`工場 ${c.facility_count}`:'工場情報なし',Number(c.label_reference_count)>0?`ラベル ${c.label_reference_count}`:'ラベル参考なし'].filter(Boolean);return `<article class="cvs-company-card"><h4>${esc(c.company_name)}</h4><div class="cvs-tags">${tags.map(t=>`<span>${esc(t)}</span>`).join('')}</div><p>${esc(c.business_product_category||'食品カテゴリ未入力')}</p><div class="cvs-meta"><span>関連チェーン: ${esc(c.related_cvs_chains||'未入力')}</span><span>主な地域: ${esc(c.main_locations||'未入力')}</span>${c.rice_related?`<span>米飯接点: ${esc(c.rice_related)}</span>`:''}</div><div class="source-links"><button data-id="${esc(c.company_id)}">詳細を見る</button>${firstSource(c)?`<a class="source-btn" href="${esc(firstSource(c))}" target="_blank" rel="noopener noreferrer">出典</a>`:''}</div></article>`}
function firstSource(c){for(const s of c.sources||[]){const u=safeUrl(s.source_url);if(u)return u}return ''}
function table(rows,cols,limit=12){if(!rows||!rows.length)return '<p class="empty-cvs">データなし</p>';const v=rows.slice(0,limit);return `<table class="mini-table"><thead><tr>${cols.map(c=>`<th>${esc(c[0])}</th>`).join('')}</tr></thead><tbody>${v.map(r=>`<tr>${cols.map(c=>`<td>${esc(r[c[1]]||'')}</td>`).join('')}</tr>`).join('')}</tbody></table>${rows.length>limit?`<p class="cvs-meta">ほか ${rows.length-limit} 件</p>`:''}`}
function showDetail(id){const c=cvsData.companies.find(x=>x.company_id===id);if(!c)return;const sourceLinks=(c.sources||[]).map(s=>{const u=safeUrl(s.source_url);return `<div class="cvs-detail-item"><strong>${esc(s.source_title||s.source_id)}</strong><p>${esc(s.source_type||'出典')}</p>${u?`<a class="source-btn" href="${esc(u)}" target="_blank" rel="noopener noreferrer">出典リンクを開く</a>`:''}</div>`}).join('')||'<p class="empty-cvs">出典なし</p>';$('#cvsDetail').innerHTML=`<h2>${esc(c.company_name)}</h2><div class="cvs-tags"><span>${esc(c.country_region)}</span><span>${esc(c.display_status)}</span><span>工場 ${esc(c.facility_count)}</span><span>ラベル ${esc(c.label_reference_count)}</span></div><div class="cvs-detail-section"><h4>関連チェーン・カテゴリ</h4><p>${esc(c.related_cvs_chains||'未入力')}</p><p>${esc(c.business_product_category||'未入力')}</p></div><div class="cvs-detail-section"><h4>関連工場・拠点</h4>${table(c.facilities,[['拠点名','factory_name'],['種別','facility_type'],['地域','city_area'],['主な品目','main_products']])}</div><div class="cvs-detail-section"><h4>商品ラベル参考</h4><p class="cvs-meta">商品ラベルは供給関係の手がかりとして表示し、工場確定情報とは分けています。</p>${table(c.product_label_references,[['商品名','product_name'],['カテゴリ','product_category'],['製造者','manufacturer'],['扱い','display_treatment']])}</div><div class="cvs-detail-section"><h4>出典</h4>${sourceLinks}</div>`;$('#cvsDialog').showModal()}
async function init(){const res=await fetch('data/cvs_vendor_master_CURRENT.json?v=240',{cache:'no-store'});cvsData=await res.json();fillStats();setupFilters();renderCountries();renderCards();['#cvsSearch','#cvsCountry','#cvsStatus','#cvsFlag'].forEach(s=>$(s).addEventListener('input',renderCards));$('#cvsCountryGrid').addEventListener('click',e=>{const b=e.target.closest('button[data-country]');if(b){$('#cvsCountry').value=b.dataset.country;renderCards();window.scrollTo({top:document.querySelector('.cvs-list-section').offsetTop-60,behavior:'smooth'});}});$('#cvsCards').addEventListener('click',e=>{const b=e.target.closest('button[data-id]');if(b)showDetail(b.dataset.id)});$('#cvsClose').addEventListener('click',()=>$('#cvsDialog').close());const btn=$('#cacheRefreshBtn');if(btn)btn.addEventListener('click',refreshMarketBaseCache);}
init();
