
const FLIGHT_VERSION='V240_CVS_VENDOR_DB_SEPARATE_PAGE_20260706';
let flightData={metadata:{},countries:[],companies:[]};
const $=s=>document.querySelector(s);
function esc(v){return String(v??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));}
function safeUrl(u){try{const x=new URL(String(u||''), location.href);return ['http:','https:'].includes(x.protocol)?x.href:'';}catch(e){return '';}}
function n(v){const x=Number(v||0);return Number.isFinite(x)?x.toLocaleString('ja-JP'):'0'}
function hasYes(v){return String(v||'').toLowerCase().includes('yes')}
async function refreshMarketBaseCache(){try{const keys=await caches.keys();await Promise.all(keys.filter(k=>k.includes('market_base')||k.includes('MARKET_BASE')).map(k=>caches.delete(k)));if('serviceWorker'in navigator){const regs=await navigator.serviceWorker.getRegistrations();await Promise.all(regs.filter(r=>String(r.scope||'').includes('/market_base/')).map(r=>r.unregister()));}location.href=location.pathname+'?v=240&refresh='+Date.now();}catch(e){location.reload();}}
function fillStats(){const m=flightData.metadata||{};$('#flightStats').innerHTML=[['会社',m.company_count],['施設',m.facility_count],['空港',m.airport_count],['案件',m.project_count]].map(([a,b])=>`<div class="flight-stat"><strong>${n(b)}</strong><span>${a}</span></div>`).join('');}
function setupFilters(){const countries=[...new Set(flightData.companies.map(x=>x.country_region).filter(Boolean))].sort();$('#flightCountry').innerHTML='<option value="all">すべての国・地域</option>'+countries.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('');const types=[...new Set(flightData.companies.map(x=>x.company_type).filter(Boolean))].sort();$('#flightType').innerHTML='<option value="all">すべての会社種別</option>'+types.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('');const params=new URLSearchParams(location.search);const country=params.get('country');if(country&&countries.includes(country))$('#flightCountry').value=country;['flightSearch','flightCountry','flightType','flightFoodFlag'].forEach(id=>$('#'+id).addEventListener('input',renderAll));}
function renderCountries(){const top=[...flightData.countries].filter(c=>c.company_count||c.facility_count).sort((a,b)=>(b.company_count+b.facility_count)-(a.company_count+a.facility_count)).slice(0,18);$('#flightCountryGrid').innerHTML=top.map(c=>`<article class="flight-country-card"><h4>${esc(c.country_region)}</h4><div class="flight-mini"><span>会社 ${n(c.company_count)}</span><span>施設 ${n(c.facility_count)}</span><span>空港 ${n(c.airport_count)}</span><span>案件 ${n(c.project_count)}</span></div><button type="button" data-country="${esc(c.country_region)}">この国を見る</button></article>`).join('');document.querySelectorAll('[data-country]').forEach(btn=>btn.addEventListener('click',()=>{$('#flightCountry').value=btn.dataset.country;renderAll();scrollTo({top:document.querySelector('.flight-list-section').offsetTop-80,behavior:'smooth'});}));}
function filtered(){const q=$('#flightSearch').value.trim().toLowerCase();const country=$('#flightCountry').value;const type=$('#flightType').value;const flag=$('#flightFoodFlag').value;return flightData.companies.filter(c=>{const hay=[c.company_name_en,c.company_name_local,c.country_region,c.company_type,c.airport_codes_display,c.public_profile_text_ja,c.menu_categories_display,c.non_airline_categories_display,(c.business_scope||[]).join(' ')].join(' ').toLowerCase();if(q&&!hay.includes(q))return false;if(country!=='all'&&c.country_region!==country)return false;if(type!=='all'&&c.company_type!==type)return false;if(flag==='rice'&&!hasYes(c.rice_menu_flag))return false;if(flag==='nonair'&&!hasYes(c.non_airline_manufacturing_flag))return false;if(flag==='project'&&Number(c.core_project_count||0)<1)return false;return true;});}
function card(c){const tags=(c.public_feature_tags_ja||[]).slice(0,4).map(t=>`<span>${esc(t)}</span>`).join('');const src=(c.sources||[])[0];const srcUrl=safeUrl(src&&src.url);return `<article class="flight-company-card"><h4>${esc(c.company_name_en)}</h4><div class="flight-meta"><span>${esc(c.country_region)} / ${esc(c.company_type)}</span><span>空港: ${esc(c.airport_codes_display||'-')}</span></div>${tags?`<div class="flight-tags">${tags}</div>`:''}<p>${esc(c.public_profile_text_ja||'')}</p><div class="flight-mini"><span>施設 ${n(c.facility_count)}</span><span>メニュー ${n(c.menu_record_count)}</span><span>案件 ${n(c.core_project_count)}</span></div><div class="source-links"><button type="button" data-detail="${esc(c.company_id)}">詳細</button>${srcUrl?`<a class="source-btn" href="${esc(srcUrl)}" target="_blank" rel="noopener">出典</a>`:''}</div></article>`}
function renderCards(){const arr=filtered();$('#flightCount').textContent=`${n(arr.length)}件`;$('#flightCards').innerHTML=arr.length?arr.map(card).join(''):'<div class="empty-flight">条件に合う表示データがありません。</div>';document.querySelectorAll('[data-detail]').forEach(b=>b.addEventListener('click',()=>openDetail(b.dataset.detail)));}
function openDetail(id){const c=flightData.companies.find(x=>x.company_id===id);if(!c)return;const facilities=(c.facilities||[]).map(f=>`<div class="flight-detail-item"><strong>${esc(f.facility_name)}</strong><br>${esc(f.city)} / ${esc(f.airport_code)} / ${esc(f.facility_type)}<br>${esc(f.products||'')}</div>`).join('');const projects=(c.projects||[]).map(p=>`<div class="flight-detail-item"><strong>${esc(p.project_title)}</strong><br>${esc(p.project_summary)}<br>${esc(p.status||'')}</div>`).join('');const sources=(c.sources||[]).map(s=>{const u=safeUrl(s.url);return u?`<a class="source-btn" href="${esc(u)}" target="_blank" rel="noopener">${esc(s.title||s.source_id)}</a>`:'';}).join('');$('#flightDetail').innerHTML=`<h3>${esc(c.company_name_en)}</h3><p>${esc(c.public_profile_text_ja||'')}</p><div class="flight-detail-section"><h4>施設</h4>${facilities||'<p>表示できる施設情報はありません。</p>'}</div><div class="flight-detail-section"><h4>プロジェクト</h4>${projects||'<p>表示できるプロジェクト情報はありません。</p>'}</div><div class="flight-detail-section"><h4>出典</h4><div class="source-links">${sources||''}</div></div>`;$('#flightDialog').showModal();}
function renderAll(){const country=$('#flightCountry').value;if(country&&country!=='all'){history.replaceState(null,'','?country='+encodeURIComponent(country));}renderCards();}
async function init(){const res=await fetch('data/flight_kitchen_master_CURRENT.json?v=240',{cache:'no-store'});flightData=await res.json();fillStats();setupFilters();renderCountries();renderAll();$('#flightClose').addEventListener('click',()=>$('#flightDialog').close());$('#cacheRefreshBtn').addEventListener('click',refreshMarketBaseCache);const lang=$('#langSelect');if(lang)lang.addEventListener('change',()=>{localStorage.setItem('mb_lang',lang.value);});}
init().catch(err=>{console.error(err);document.body.insertAdjacentHTML('beforeend','<div class="empty-flight">データを読み込めませんでした。</div>')});
