const FLIGHT_VERSION='V243_CVS_PASS53_RC_V5_DISPLAY_REPLACE_20260707';
let flightData={metadata:{},cards:[],details:[],search:[]};
const $=s=>document.querySelector(s);
function esc(v){return String(v??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));}
function n(v){const x=Number(v||0);return Number.isFinite(x)?x.toLocaleString('ja-JP'):'0'}
function yes(v){return String(v||'').toLowerCase().includes('yes') || v===true}
const companyTypeLabel={
  airline_owned_caterer:'航空会社系ケータリング', independent_caterer:'ケータリング会社', airport_caterer:'空港ケータリング', ground_handler_catering:'空港サービス系', airline_internal_catering_and_food_services:'航空会社内製・食品サービス', local_airline_catering_company_candidate:'地域航空ケータリング', food_manufacturer:'食品製造会社', logistics_food_service:'食品物流・供給'
};
const facilityTypeLabel={flight_kitchen:'機内食キッチン', catering_unit:'ケータリング拠点', food_factory:'食品工場', central_kitchen:'セントラルキッチン'};
function labelType(v){return companyTypeLabel[v] || String(v||'').replaceAll('_',' ')}
function labelFacility(v){return facilityTypeLabel[v] || String(v||'').replaceAll('_',' ')}
async function refreshMarketBaseCache(){try{const keys=await caches.keys();await Promise.all(keys.filter(k=>k.includes('market_base')||k.includes('MARKET_BASE')).map(k=>caches.delete(k)));if('serviceWorker'in navigator){const regs=await navigator.serviceWorker.getRegistrations();await Promise.all(regs.filter(r=>String(r.scope||'').includes('/market_base/')).map(r=>r.unregister()));}location.href=location.pathname+'?v=243&refresh='+Date.now();}catch(e){location.reload();}}
function fillStats(){const c=flightData.metadata?.counts||{};$('#flightStats').innerHTML=[['会社',c.company_cards||flightData.cards.length],['施設',c.facilities],['空港',c.airports],['案件',c.projects]].map(([a,b])=>`<div class="flight-stat"><strong>${n(b)}</strong><span>${a}</span></div>`).join('');}
function setupFilters(){const countries=[...new Set(flightData.cards.map(x=>x.country_region).filter(Boolean))].sort();$('#flightCountry').innerHTML='<option value="all">すべての国・地域</option>'+countries.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('');const types=[...new Set(flightData.cards.map(x=>x.company_type).filter(Boolean))].sort();$('#flightType').innerHTML='<option value="all">すべての会社種別</option>'+types.map(c=>`<option value="${esc(c)}">${esc(labelType(c))}</option>`).join('');const params=new URLSearchParams(location.search);const country=params.get('country');if(country&&countries.includes(country))$('#flightCountry').value=country;['flightSearch','flightCountry','flightType','flightFoodFlag'].forEach(id=>$('#'+id).addEventListener('input',renderAll));}
function countryRows(){const map=new Map();for(const c of flightData.cards){const key=c.country_region||'その他';const r=map.get(key)||{country_region:key,company_count:0,facility_count:0,airport_codes:new Set(),project_count:0};r.company_count++;r.facility_count+=Number(c.facility_count||0);(c.airport_codes||[]).forEach(a=>r.airport_codes.add(a));r.project_count+=Number(c.core_project_count||0);map.set(key,r);}return [...map.values()].map(r=>({...r,airport_count:r.airport_codes.size}));}
function renderCountries(){const top=countryRows().sort((a,b)=>(b.company_count+b.facility_count)-(a.company_count+a.facility_count)).slice(0,18);$('#flightCountryGrid').innerHTML=top.map(c=>`<article class="flight-country-card"><h4>${esc(c.country_region)}</h4><div class="flight-mini"><span>会社 ${n(c.company_count)}</span><span>施設 ${n(c.facility_count)}</span><span>空港 ${n(c.airport_count)}</span><span>案件 ${n(c.project_count)}</span></div><button type="button" data-country="${esc(c.country_region)}">この国を見る</button></article>`).join('');document.querySelectorAll('[data-country]').forEach(btn=>btn.addEventListener('click',()=>{$('#flightCountry').value=btn.dataset.country;renderAll();scrollTo({top:document.querySelector('.flight-list-section').offsetTop-80,behavior:'smooth'});}));}
function filtered(){const q=$('#flightSearch').value.trim().toLowerCase();const country=$('#flightCountry').value;const type=$('#flightType').value;const flag=$('#flightFoodFlag').value;const searchMap=new Map(flightData.search.map(s=>[s.id,String(s.search_text||'').toLowerCase()]));return flightData.cards.filter(c=>{const hay=(searchMap.get(c.company_id)||[c.name,c.country_region,labelType(c.company_type),(c.airport_codes||[]).join(' '),c.summary_ja,(c.feature_tags_ja||[]).join(' ')].join(' ').toLowerCase());if(q&&!hay.includes(q))return false;if(country!=='all'&&c.country_region!==country)return false;if(type!=='all'&&c.company_type!==type)return false;if(flag==='rice'&&!yes(c.rice_menu))return false;if(flag==='nonair'&&!yes(c.non_airline_food_manufacturing))return false;if(flag==='project'&&Number(c.core_project_count||0)<1)return false;return true;});}
function card(c){const tags=(c.feature_tags_ja||[]).slice(0,3).map(t=>`<span>${esc(t)}</span>`).join('');const airports=(c.airport_codes||[]).slice(0,5).join(' / ');return `<article class="flight-company-card"><h4>${esc(c.name)}</h4><div class="flight-meta"><span>${esc(c.country_region)} / ${esc(labelType(c.company_type))}</span>${airports?`<span>空港: ${esc(airports)}</span>`:''}</div>${tags?`<div class="flight-tags">${tags}</div>`:''}<p>${esc(c.summary_ja||'')}</p><div class="flight-mini"><span>施設 ${n(c.facility_count)}</span><span>案件 ${n(c.core_project_count)}</span></div><div class="source-links"><button type="button" data-detail="${esc(c.company_id)}">詳細</button></div></article>`}
function renderCards(){const arr=filtered();$('#flightCount').textContent=`${n(arr.length)}件`;$('#flightCards').innerHTML=arr.length?arr.map(card).join(''):'<div class="empty-flight">条件に合うデータがありません。</div>';document.querySelectorAll('[data-detail]').forEach(b=>b.addEventListener('click',()=>openDetail(b.dataset.detail)));}
function itemList(title, rows){return rows&&rows.length?`<div class="flight-detail-section"><h4>${esc(title)}</h4>${rows.join('')}</div>`:''}
function openDetail(id){const c=flightData.details.find(x=>x.company_id===id);if(!c)return;const facilities=(c.facilities||[]).map(f=>{const aps=(f.airports||[]).map(a=>`${a.iata||''} ${a.name||''}`.trim()).filter(Boolean).join(' / ');return `<div class="flight-detail-item"><strong>${esc(f.name)}</strong><br>${esc([f.city,labelFacility(f.facility_type)].filter(Boolean).join(' / '))}${aps?`<br>空港: ${esc(aps)}`:''}</div>`});const menus=(c.menus||[]).slice(0,8).map(m=>`<div class="flight-detail-item"><strong>${esc(m.menu_examples||'メニュー')}</strong><br>${esc(m.cuisine_or_cultural_theme||'')}</div>`);const businesses=(c.non_airline_food_business||[]).map(b=>`<div class="flight-detail-item">${esc(b.description||'')}</div>`);const projects=(c.projects||[]).map(p=>`<div class="flight-detail-item"><strong>${esc(p.title)}</strong><br>${esc(p.summary||'')}${p.investment_amount?`<br>投資: ${esc(p.investment_amount)}`:''}${p.capacity_change?`<br>能力: ${esc(p.capacity_change)}`:''}</div>`);$('#flightDetail').innerHTML=`<h3>${esc(c.name)}</h3>${c.local_name?`<p class="subnote">${esc(c.local_name)}</p>`:''}<p>${esc(c.profile?.ja||'')}</p><div class="flight-tags">${((c.summary?.feature_tags_ja)||[]).map(t=>`<span>${esc(t)}</span>`).join('')}</div>${itemList('拠点・空港',facilities)}${itemList('メニュー',menus)}${itemList('機内食以外の食品事業',businesses)}${itemList('関連案件',projects)}`;$('#flightDialog').showModal();}
function renderAll(){const country=$('#flightCountry').value;if(country&&country!=='all'){history.replaceState(null,'','?country='+encodeURIComponent(country));}renderCards();}
async function loadJson(name){return fetch(`data/flight_kitchen_public_ui/${name}?v=243`,{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error(name);return r.json();});}
async function init(){const [metadata,cards,details,search]=await Promise.all([loadJson('metadata.json'),loadJson('company_cards.json'),loadJson('company_details.json'),loadJson('search_index.json')]);flightData={metadata,cards,details,search};fillStats();setupFilters();renderCountries();renderAll();$('#flightClose').addEventListener('click',()=>$('#flightDialog').close());$('#cacheRefreshBtn').addEventListener('click',refreshMarketBaseCache);const lang=$('#langSelect');if(lang)lang.addEventListener('change',()=>{localStorage.setItem('mb_lang',lang.value);});}
init().catch(err=>{console.error(err);document.body.insertAdjacentHTML('beforeend','<div class="empty-flight">データを読み込めませんでした。</div>')});
